blendersite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('create/', views.create_post, name='create'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='category'),
    path('categories/<int:category_id>', views.detail_category, name='detailcategory'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField()
    image_url = models.URLField(max_length=200, null=True)
    content = models.TextField()

    def __str__(self):
        return f'{self.title} ({self.date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    date = models.DateTimeField()
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'date',
            'image_url',
            'content'
        ]
        labels = {
            'title': 'Título',
            'date': 'Data de Postagem',
            'image_url': 'URL da Imagem',
            'content': 'Conteúdo'
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'date',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'date': 'Data',
            'text': 'Comentário',
        }

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .temp_data import post_data
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)


def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'posts/detailcategory.html', context)


def list_posts(request):
    post_list = Post.objects.all()
    context = {"post_list": post_list}
    return render(request, 'posts/index.html', context)


class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories.html'


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_title = form.cleaned_data['title']
            post_date = form.cleaned_data['date']
            post_image_url = form.cleaned_data['image_url']
            post_content = form.cleaned_data['content']
            post = Post(title=post_title,
                        date=post_date,
                        image_url=post_image_url,
                        content=post_content)
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'posts/create.html', context)


def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.date = form.cleaned_data['date']
            post.image_url = form.cleaned_data['image_url']
            post.content = form.cleaned_data['content']
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'title': post.title,
                'date': post.date,
                'image_url': post.image_url,
                'content': post.content
            })

    context = {'post': post, 'form': form}
    return render(request, 'posts/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_date = form.cleaned_data['date']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            date=comment_date,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    <hr>
    <article>
        <header>
            <h3>{{category.name}}</h3>
        </header>
        <div class="lista-de-cards">
            {% for category in category_list %}
                <div class="card">
                    <a href="{% url 'posts:detailcategory' category.id %}"><h1>{{category.name}}</h1></a>
                    <p>{{ category.description }}</p>
                </div>
            {% endfor %}
        </div>
    </article>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Post {{ post.title }} ({{ post.date }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o filme "{{ post.title }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ post.title }}</h2>

<section class="dados-de-filme">
    <img src="{{ post.image_url }}" alt="Poster do filme {{ post.title}}">
    <ul>
        <li>Título: {{ post.title }}</li>
        <li>Data da Postagem: {{ post.date|date:"d/m/y" }} </li>
        <li>Conteúdo: {{ post.content|safe }}</li>
        {% if post.category_set.all %}
            <li>Categorias: {{ post.category_set.all|join:", "}}</li>
        {% endif %}
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }} ({{ comment.date|date:"d/m/y" }})
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este filme.</p>
        {% endif %}
    </ul>
</section>

<a href="{% url 'posts:comment' post.pk %}"><button>Crie seu Comentário</button></a>
</section>

{% endblock content %}

posts/templates/posts/detailcategory.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}
<h2>Posts dentro da Categoria {{ category.name }}</h2>

<section>
    <hr>
    <article>
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
                        alt="Poster do filme {{ post.title}}"></a>
                <p>{{ post.title }} ({{ post.date|date:"d/m/y" }})</p>
            </div>
            {% endfor %}
        </div>
    </article>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <h1>{{ post.title }}</h1>
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
            alt="Poster do filme {{ post.title}}"></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.image_url }}" alt="Poster do filme {{ post.title}}">
        <p>{{ post.title }} ({{ post.date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Post {{ movie.name }}</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Your Blender Room</i></h1>
<p>A Página para Comunidade de Amantes de Quartos Isométricos criados no Blender</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Your Blender Room
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'new_style.css' %}">
</head>


<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'new_logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li>
                <li><a href="{% url 'posts:category' %}">Categorias</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>